source "http://rubygems.org"
gem "sinatra", "1.4.3"
gem "rack", "1.5.2"
gem "haml", "3.1.7"
gem "sinatra-flash","0.3.0"
gem "sqlite3"
gem "activerecord"
gem "sinatra-activerecord"
gem "data_mapper"
gem "dm-sqlite-adapter"
gem "rake"
